### ISSUE TITLE
Should it be MSE rather than BCE loss?

### ISSUE THREAD

**Issue by HeroKillerEver** [yunjey/pytorch-tutorial#104]
https://github.com/yunjey/pytorch-tutorial/blob/6c785eb810848f259431865b12bb8795f4abcb23/tutorials/03-advanced/variational_auto_encoder/main.py#L79

**Comment by yunjey** [comment]
@HeroKillerEver Sorry for late reply. For binary data (e.g., MNIST 0~1), we can use BCE loss as reconstruction loss. However, it does not matter if you replace BCE loss with MSE.
