### ISSUE TITLE
LSTM tutorials on video processing

### ISSUE THREAD

**Issue by niuqun** [yunjey/pytorch-tutorial#105]
Dear all, do you have tutorials for video processing using LSTM? I am sorry to ask this but I am new to the PyTorch and do not know how to implement this. Thanks!

**Comment by hichoe95** [comment]
https://www.youtube.com/watch?v=SKq-pmkekTk&list=PLlMkM4tgfjnJ3I-dbhO9JTw7gNty6o_2m

I recommend this video lecture to you .

**Comment by icfear** [comment]
You can look at [https://github.com/bharathgs/Awesome-pytorch-list](url) for a few related examples.
