### ISSUE TITLE
How to create two convolution kernel that share same variable but different dilation

### ISSUE THREAD

**Issue by rocknamx8** [yunjey/pytorch-tutorial#110]
I want to create two dilated convolution kernel with different dilation, but how can I make them share their variable.
(　ﾟдﾟ)

**Comment by yunjey** [comment]
It is more helpful for you to post this issue on PyTorch forums.

**Comment by srinadhu** [comment]
Use the F.conv2d() function. i.e. F.conv2d(input, put the layer weights you want to share, put the layer bias you want to share, padding, dilation). Hope this helps.
