### ISSUE TITLE
Image Captioning: where can I get the ./data/vocab.pkl?

### ISSUE THREAD

**Issue by x11wu** [yunjey/pytorch-tutorial#123]
when running `build_vocab.py`, it warns "IOError: [Errno 2] No such file or directory: './data/vocab.pkl'"

**Comment by yunjey** [comment]
If you want to use the pretrained model for image captioning, see [here](https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/03-advanced/image_captioning#pretrained-model).
