### ISSUE TITLE
"value.grad" has no attribute 'data'

### ISSUE THREAD

**Issue by KingofAsianPopJC** [yunjey/pytorch-tutorial#133]
When the python program run to the code of visualizing the parameter of the model : "value.grad.data.cpu().numpy()", 
error raises : Nonetype Object has no attribute 'data'
So if I want to visualize the grad of the parameters, what should i do?

**Comment by yunjey** [comment]
You should run backward to get meaningful gradients. The error message says that there is no gradient in value tensor.
