### ISSUE TITLE
 No such file or directory: 'models/encoder-2-1000.ckpt'

### ISSUE THREAD

**Issue by KahHwa** [yunjey/pytorch-tutorial#134]
I downloaded the pretrained model to use. But I don't have the models/encoder-2 1000.ckpt' file. What I have from the model.zip are just "decoder-5 3000.pkl" and "encoder-5 3000.pkl".

**Comment by shaunVB** [comment]
> I downloaded the pretrained model to use. But I don't have the models/encoder-2 1000.ckpt' file. What I have from the model.zip are just "decoder-5 3000.pkl" and "encoder-5 3000.pkl".

How did you solved it ?

**Comment by anjalinagel12** [comment]
> I downloaded the pretrained model to use. But I don't have the models/encoder-2 1000.ckpt' file. What I have from the model.zip are just "decoder-5 3000.pkl" and "encoder-5 3000.pkl".

getting the same problem.. how to solve it?

**Comment by anjalinagel12** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder-2-1000.ckpt'
someone please help

**Comment by anjalinagel12** [comment]
> > I downloaded the pretrained model to use. But I don't have the models/encoder-2 1000.ckpt' file. What I have from the model.zip are just "decoder-5 3000.pkl" and "encoder-5 3000.pkl".
> 
> How did you solved it ?

Anyone?

**Comment by syedimad1998** [comment]
@anjalinagel12 rename the encoder and decoder file name.
encoder-5 3000.pkl file name to encoder-2-1000.ckpt worked for me.Hope it helps!

**Comment by anjalinagel12** [comment]
Anjalis-MacBook-Air:image_captioning ANJALI$ python sample.py --image='png/example.png'
Traceback (most recent call last):
  File "sample.py", line 81, in <module>
    main(args)
  File "sample.py", line 43, in main
    encoder.load_state_dict(torch.load(args.encoder_path))
  File "/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 356, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder-2-1000.ckpt'

**Comment by anitchakraborty** [comment]
> @anjalinagel12 rename the encoder and decoder file name.
> encoder-5 3000.pkl file name to encoder-2-1000.ckpt worked for me.Hope it helps!

Not helped. Is there any other solution?
