### ISSUE TITLE
[Image Captioning] Training gets stuck after first iteration

### ISSUE THREAD

**Issue by umerebryx** [yunjey/pytorch-tutorial#14]
Hi,

I have tested your train.py script in captioning tutorial to run over my custom dataset. After some debugging it seems the script is not looping back after the first iteration. [This](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/09%20-%20Image%20Captioning/train.py#L77) is last line executed by the script and then I don't see any output for hours. Below is the output of the script:
```
python train.py 
Epoch [0/5], Step [0/22], Loss: 4.7755, Perplexity: 118.5671
```
Have you tested this on custom dataset? Can I get some pointers what might be wrong here.

Thanks

**Comment by yunjey** [comment]
Did you use GPU? Image captioning has a long training time. For Pascal Titan X, it took about 1 hour per epoch. [Here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/09%20-%20Image%20Captioning/configuration.py#L33) you can reduce the log_step.

**Comment by umerebryx** [comment]
Thanks for the reply. Yes, I am using gpu I will reduce the log steps and update here.
