### ISSUE TITLE
'models/encoder-2-1000.ckpt' file not found

### ISSUE THREAD

**Issue by anjalinagel12** [yunjey/pytorch-tutorial#155]
No such file or directory: 'models/encoder-2-1000.ckpt'

I downloaded the pretrained model to use. But I don't have the models/encoder-2 1000.ckpt' file. What I have from the model.zip are just "decoder-5 3000.pkl" and "encoder-5 3000.pkl".

**Comment by yunjey** [comment]
You can change the configuration [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/sample.py#L72-L73) (from`2-1000.ckpt` to `5-3000.pkl`)

**Comment by anjalinagel12** [comment]
Hey,

I am getting this error. Please help me.

**Comment by anjalinagel12** [comment]
Thanks, it worked. :)
