### ISSUE TITLE
second epoch weights issues

### ISSUE THREAD

**Issue by sujayr91** [yunjey/pytorch-tutorial#18]
Hi,

Looks like the weights starting from the second epoch, gives an issue while testing with sample image.
The output is only sequence of start <start> <start>...<start>
When i debugged, I see that the "outputs"  tensor array in model.py contains all  "nan"

**Comment by yunjey** [comment]
@sujayr91 I don't understand what you are asking.. What do you mean by 'weights starting from the second epoch'?

**Comment by sujayr91** [comment]
Hi yunjey,

The model parameters I am talking are with respect to files which will be saved in model/ during training epochs. First I trained the model for Coco dataset.  While testing sample.py,  if i choose model parameters any where starting from second epoch (for example encoder-2-1000.pkl , and decoder-2-1000.pkl) I get output caption as <start> <start> <start> <start>....... 

I will check your pretrained model also. 

Thanks

**Comment by yunjey** [comment]
Oh, I think you should change the code in configuration.py. 

I deleted the configuration.py file and add argparse to control the arguments. Please check the code.
