### ISSUE TITLE
RNN input size question 

### ISSUE THREAD

**Issue by OrangeC93** [yunjey/pytorch-tutorial#195]
I'm new to pytorch, Can anyone answer my question which confused me a lot:

[In RNN tutorial](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/recurrent_neural_network/main.py)

images are reshaped into (batch, seq_len, input_size)
```
images = images.reshape(-1, sequence_length, input_size)
```

But What I learned input dimensions should be (seq_len, batch, input_size)?

**Comment by GatoY** [comment]
Hi @OrangeC93,

```
self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
```
See "batch_first = True". But in default "batch_first = False".

That's the reason. U can refer to the source code of RNN cell. [here]("https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py")

**Comment by OrangeC93** [comment]
> Hi @OrangeC93,
> 
> ```
> self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)
> ```
> 
> See "batch_first = True". But in default "batch_first = False".
> 
> That's the reason. U can refer to the source code of RNN cell. [here](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/rnn.py)

wow~ I got it! Many thanks!
