### ISSUE TITLE
How to use pretrained model?

### ISSUE THREAD

**Issue by HiiYL** [yunjey/pytorch-tutorial#20]
In the folder "09 - Image Captioning", you provided the pretrained model in the form of a .egg file. May i ask how do i use the downloaded file?

I tried extracting it by renaming the file to a .zip file, but it did not work.

Executing the egg file as Python package also gave the error:
SyntaxError: Non-UTF-8 code starting with '\xeb' in file trained_model.egg on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by yunjey** [comment]
@HiiYL sorry for that. I will upload .zip file soon instead of .egg file.

**Comment by yunjey** [comment]
Now, i uploaded .zip file. Good luck!
