### ISSUE TITLE
[Image Captioning] High GPU memory usage when using pytorch 0.11 for image captioning

### ISSUE THREAD

**Issue by hanzhanggit** [yunjey/pytorch-tutorial#26]
Hi,
I am running the 09 image captioning model. When I used the pytorch 0.10, I can set the batchsize to be 512 (takes around 8G for the GPU memory). But when I upgrade to pytorch 0.11， the maximum batchsize I can set is only around 30 (takes around 11G GPU memory). I am confused since the codebase is mainly the basic CNN and lstm models. Do you know where the problem comes from? Have you tried to upgrade to pytorch 0.11 to run it?  

By the way, I am using Tesla K40c GPU. 
pytorch 0.10:  0.1.10+ac9245a
pytorch 0.11: same problem with (0.1.11_5 and 0.1.11+b13b701)

**Comment by hanzhanggit** [comment]
When I dig into the code, I found the major issue is due to 
[features = self.resnet(images) ](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/09%20-%20Image%20Captioning/model.py#L26)
But I don't know why  pytorch 0.11 takes much more memory compared to pytorch 0.10

**Comment by hanzhanggit** [comment]
I also post this problem [here](https://discuss.pytorch.org/t/high-gpu-memory-usage-for-resnet-models-in-pytorch-0-1-11-compared-to-0-1-10/2472)

**Comment by yunjey** [comment]
This is PyTorch version issue. You can see [here](https://discuss.pytorch.org/t/params-requires-grad-false-has-elevated-memory-usage-in-v0-1-11/1625). You can solve this problem if you use Python 3.5 instead of 2.7. Also, you can fix this problem by replacing 'requires_grad' to 'volatiles'. 

This issue is automatically resolved when a new version of PyTorch is released.

**Comment by hanzhanggit** [comment]
Hi,

Thanks for the reply. It seems that the problem is still there for pytorch
0.1.12. In addition, for my user case, I need to fine-tune on top of resnet
models, I think the volatiles did not work for since it will neglect all
the grad for the whole network.

Best,
Han

2017-04-27 20:38 GMT-04:00 yunjey <notifications@github.com>:

**Comment by karandwivedi42** [comment]
+1 Using pytorch 0.1.12 on python 3.6, the problem still exists.

**Comment by jtoy** [comment]
great, looking forward to testing this. I think im running into a similar issue.

**Comment by yunjey** [comment]
Now, i fixed this issue using `volatile `and `children`.
