### ISSUE TITLE
[Image Captioning] Pretrained model can't be used

### ISSUE THREAD

**Issue by deltawing** [yunjey/pytorch-tutorial#33]
when i reach that link,it show 404 not found.

**Comment by jtoy** [comment]
do you have more info? I had a similar issue and I just used wget instead of python's libraries.

**Comment by yunjey** [comment]
@deltawing I will upload it again soon.

**Comment by yunjey** [comment]
@deltawing I uploaded the zip file for the pretrained model. check [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/README.md#pretrained-model)
