### ISSUE TITLE
[image captioning] training /test/validation data?

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#37]
training /test/validation data? I saw in image captioning and the other examples that there is no training/test/validation splits.  Should the examples have this to promote best practices? If I wrote code to add it, would it be merged in?

**Comment by yunjey** [comment]
@jtoy Official MSCOCO dataset has only train/val split. Use karpathy split (110000 for train and 5000 for val/test). This is beyond the tutorial.
