### ISSUE TITLE
graph visualization in tensorboard with pytorch?

### ISSUE THREAD

**Issue by EmbraceLife** [yunjey/pytorch-tutorial#43]
Hi, thanks a lot for this wonderful repo and recent work on tensorboard!

I just wonder when would be graph visualization of tensorboard for pytorch could be available. 
any idea? 

Thanks again for your great work!

**Comment by yunjey** [comment]
@EmbraceLife As far as I know, currently we can not easily visualize the graph using TensorBoard in PyTorch.
See [here](https://discuss.pytorch.org/t/print-autograd-graph/692/2?u=xwgeng) to visualize the model using another way.
