### ISSUE TITLE
TensorBoard example: net object has no attribute named_parameters?

### ISSUE THREAD

**Issue by yenson-lau** [yunjey/pytorch-tutorial#46]
Hi, I'm a bit new to PyTorch / Python so I apologize if I made a poor diagnosis in advance. My error is of the following form when running `main.py`

```
python main.py       
Step [100/50000], Loss: 2.1832, Acc: 0.51

Traceback (most recent call last):
  File "main.py", line 94, in <module>
    for tag, value in net.named_parameters():
  File "/home/yenson/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 237, in __getattr__
    return object.__getattr__(self, name)
AttributeError: type object 'object' has no attribute '__getattr__'```

**Comment by yunjey** [comment]
@yenson-lau Please give me more information about your error.

**Comment by kamabdi** [comment]
Update till the most recent version of PyTorch solved this issue for me.

**Comment by joehoeller** [comment]
I still have this problem and I am using a current version on CUDA-X:

`for name, param in network.named_parameters():
    print(name, '\t\t', param.shape)`

`AttributeError                            Traceback (most recent call last)
<ipython-input-140-be0d90186358> in <module>
      1 # Accessing the Networks Parameters
----> 2 for name, param in network.named_parameters():
      3     print(name, '\t\t', param.shape)

AttributeError: 'Network' object has no attribute 'named_parameters'`
