### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#5]
There are many libraries needed to run these tutorials. lets add the requirements in a file to make it easy to run these.

**Comment by stephenbhope** [comment]
I would like to work on this.

**Comment by yunjey** [comment]
If you installed Python using anaconda, numpy and matplotlib are basically there.

Except for image captioning and dqn examples, you don't need to install libraries other than [pytorch and  torch-vision](http://pytorch.org/). For image captioning and dqn examples, i will add README.md to help people to install the required libraries easily soon.

**Comment by yunjey** [comment]
I added requirements.txt for image captioning. It would be helpful.
