### ISSUE TITLE
datasets for models

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#51]
can you provide links to the datasets you use?
in particular whihc treebank dataset are you using here: https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/language_model/main.py#L20 ?
Im trying to replicate  your tutorials down to  exact data.

**Comment by yunjey** [comment]
@jtoy You can find train.txt from "tutorials/02-intermediate/language_model/data".
referenced from [here](https://github.com/pytorch/examples/tree/master/word_language_model/data/penn).
