### ISSUE TITLE
question on different implementations

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#52]
Love the tutorials.
I see that for the RNNs you  use variable length data. Some of the tutorials use pack_padded_Sequence and not, for example this RNN uses one:
https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/model.py#L52
but this one doesnt:
https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/language_model/main-gpu.py#L32

Why do you do it like this? Is pack_padded_sequence needed? Could both of those models be written with and without pack_padded_sequence

**Comment by yunjey** [comment]
`pack_padded_sequence` is optional. In Language Mode, the input is not variable-length so you don't need to use `pack_padded_seqeuence`. For image captioning or other seq2seq task such as NMT and QA, we should deal with variable-length sequences. In these cases, we can use `pack_padded_sequence` to efficiently forward propagate the input to RNN. Again, `pack_padded_sequence` is optional not compulsory, you can just pad the input sequence, make it as a 3D tensor, forward propagate to RNN and compute loss with masking.
