### ISSUE TITLE
i have a problem of image caption,can i use another language?

### ISSUE THREAD

**Issue by BlueMyOcean** [yunjey/pytorch-tutorial#53]
I try to train model by using my own datasets, but i have a problem of character encoding, i try to change the caption into Chinese, but the vab.pkl has many ' S'\xe7\xba\xa6' ' and when i use my trained model,it always gives /</start/>/</unk/>/</end/>/ ,so, could you please tell me how to solve this problem?Thank you very much.

**Comment by BlueMyOcean** [comment]
/<  start />   /<unk />  /<end />

**Comment by BlueMyOcean** [comment]
oh, i can't type /<  ,it's like      start   unk  end

**Comment by jtoy** [comment]
try encoding it into utf8 first.

**Comment by BlueMyOcean** [comment]
@jtoy but the pkl file can only save as ascii or binary

**Comment by BlueMyOcean** [comment]
@jtoy the word i saved become S'\xe7\xba\xa6 '  in python 2.7

**Comment by BlueMyOcean** [comment]
So, should i create my own txt file to instead of pkl ?

**Comment by BlueMyOcean** [comment]
@yunjey do you have any idea of this?i'm so confused.

**Comment by BlueMyOcean** [comment]
Ok, seems like nobody can help.QAQ
