### ISSUE TITLE
found bug in variational auto encoder

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#57]
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    torchvision.utils.save_image(fixed_x.data.cpu(), './data/real_images.png')
AttributeError: 'torch.FloatTensor' object has no attribute 'data'
just move to_var above save,here is what it should be:

```
--- a/tutorials/03-advanced/variational_auto_encoder/main.py
+++ b/tutorials/03-advanced/variational_auto_encoder/main.py
@@ -65,8 +65,8 @@ data_iter = iter(data_loader)
 # fixed inputs for debugging
 fixed_z = to_var(torch.randn(100, 20))
 fixed_x, _ = next(data_iter)
-torchvision.utils.save_image(fixed_x.data.cpu(), './data/real_images.png')
 fixed_x = to_var(fixed_x.view(fixed_x.size(0), -1))
+torchvision.utils.save_image(fixed_x.data.cpu(), './data/real_images.png')
```

**Comment by yunjey** [comment]
This issue is solved [here](https://github.com/yunjey/pytorch-tutorial/pull/58).
