### ISSUE TITLE
The implemention of the downsample of the Residual network 18-layers

### ISSUE THREAD

**Issue by shendaizi** [yunjey/pytorch-tutorial#59]
@yunjey ,Hi, when I read the code of "pytorch-tutorial/tutorials/02-intermediate/deep_residual_network/main.py", I find your implemention of the "_make_layer" function usese the function "conv3_3" to do the downsample, but whether it should use the "1_1 conv", it makes me confused.

**Comment by yunjey** [comment]
@shendaizi I think this doesn't matter. You can use both 1x1 conv or 3x3 conv for downsampling.
