### ISSUE TITLE
how to load the model file in .pkl form

### ISSUE THREAD

**Issue by liuzhihui2046** [yunjey/pytorch-tutorial#6]
hello, i noticed that you have saved the model in .pkl form : torch.save(file,'model.pkl'),then how to using this model?

**Comment by yunjey** [comment]
You can load and test the model in a simple way as below.

# Load the model
model = torch.load('model.pkl')

# Test the model
outputs = model(images)

**Comment by liuzhihui2046** [comment]
when I save the model like this : model=torch.save(model,savedir),I can't load the saved model correctly.however,when save model using  model=torch.save(model.state_dict(),savedir),it works

**Comment by yunjey** [comment]
@liuzhihui2046 Thank you for letting me know the error. I modified the tutorial code to use `torch.save(model.state_dict(), save_dir)`. I don't know what caused the problem. I think it would be nice to ask this question [here](https://discuss.pytorch.org/).

**Comment by raoanonymous** [comment]
@yunjey , I am using the pre-trained model, and they are in ".pkl" format. When I try to test the model using them I am facing this issue: 

> python sample.py --image='png/example.png'
> 
> Traceback (most recent call last):
>   File "sample.py", line 81, in <module>
>     main(args)
>   File "sample.py", line 43, in main
>     encoder.load_state_dict(torch.load(args.encoder_path))
>   File "/home/pramod/anaconda3/envs/py35th/lib/python3.5/site-packages/torch/serialization.py", line 301, in load
>     f = open(f, 'rb')
> FileNotFoundError: [Errno 2] No such file or directory: 'models/encoder-2-1000.ckpt'

My folder structure: 
> ~/pytorch-tutorial/tutorials/03-advanced/image_captioning/models: 
> ` >>>ls`
> decoder-5-3000.pkl   encoder-5-3000.pkl  pretrained_model.zip

Could you please help me out?

 `

**Comment by ghost** [comment]
> You can load and test the model in a simple way as below.
> 
> ```python
> model = torch.load('model.pkl')
> outputs = model(images)
> ```

_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

I keep getting this error!!!!
How to resolve this?
