### ISSUE TITLE
No scalar data was found.

### ISSUE THREAD

**Issue by micklexqg** [yunjey/pytorch-tutorial#63]
Hi, yunnjey. thanks for your work. I run your demo, but it doesn't seem to work.
![image](https://user-images.githubusercontent.com/13776012/30642495-b616c58a-9e3d-11e7-92e8-9766d847d883.png)
 what's strange is that there is tf events under the log files. so is there any thing wrong?

**Comment by yunjey** [comment]
@micklexqg It works well. Did you solve the problem? 

In my case, the version of the tensorflow is 1.2 and pytorch is 0.2.
What version of the tensorflow are you using?

![image](https://user-images.githubusercontent.com/15663219/30952729-f5409f02-a463-11e7-80ba-5b32272e1458.png)

**Comment by micklexqg** [comment]
@yunjey , thank you, I have figured out. it's the problem of windows version.

**Comment by MarkVdBergh** [comment]
@micklexqg I have the same problem. How did you solve it?

**Comment by micklexqg** [comment]
@MarkVdBergh , need to be Google browser.
