### ISSUE TITLE
Train Image Captioning Code on Other Datasets

### ISSUE THREAD

**Issue by ahkarami** [yunjey/pytorch-tutorial#66]
@yunjey How we can train your image captioning code on another dataset? If we prepare a JSON file like (http://msvocds.blob.core.windows.net/annotations-1-0-3/captions_train-val2014.zip) the code can be trained on a new dataset?

**Comment by yunjey** [comment]
@ahkarami  Sorry for late reply. You can prepare a JSON file in the same form as MSCOCO dataset and use the code in the tutorial. Another way is to implement your own DataSet class. See [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/data_loader.py#L13-L53) for how to implement custom dataset in PyTorch.

**Comment by ahkarami** [comment]
Dear @yunjey,
Thank you very much for your response. Just as another question, would you please tell me that your nice Image Captioning code supports _Multi-GPU_ training or not?

**Comment by yunjey** [comment]
@ahkarami No, it does not support. However, you can solve the problem by using the [DataParallel](http://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html) module, or you can spread modules over multiple GPUs by passing an additional argument to `.cuda()`. For example, `.cuda(1)` will place the tensors and modules on 2nd GPU. For this, you should edit [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/train.py#L16) and [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/03-advanced/image_captioning/train.py#L47-L49).

**Comment by ahkarami** [comment]
Dear @yunjey, Thank you very much for your time and useful response.

**Comment by abhigoku10** [comment]
@ahkarami @yunjey  hi guys i am new to this topic i need to train for a custom dataset can you pls elaborate the steps for training with custom datasets . These are the things i am having currently with me

1.10k img database of various objects and tags for each image 

Thanks in advance

**Comment by ahkarami** [comment]
Dear @abhigoku10,
You can use [image captioning codebase in pytorch](https://github.com/ruotianluo/ImageCaptioning.pytorch) instead of above code. Actually, as I remember, I haven't use above code for training on another data sets, but by using the mentioned code I have done that. However, as I have remembered, that was a semi-sophisticated work to create a json file like the used one for MS-COCO.

**Comment by Kyfafyd** [comment]
Dear @yunjey 
I want to train the model on my dataset, but it seems that my json file works wrong, could you tell me how to preprocess a json file?
Thanks very much
