### ISSUE TITLE
I met this error in deep_convolution_gan.py

### ISSUE THREAD

**Issue by bemoregt** [yunjey/pytorch-tutorial#67]
Hi, @jtoy @hunkim @Kongsea @DingKe @JayParks 

I met this error in deep_convolution_gan.py :

usage: ipykernel_launcher.py [-h] [--image_size IMAGE_SIZE] [--z_dim Z_DIM]
                             [--g_conv_dim G_CONV_DIM]
                             [--d_conv_dim D_CONV_DIM]
                             [--num_epochs NUM_EPOCHS]
                             [--batch_size BATCH_SIZE]
                             [--sample_size SAMPLE_SIZE]
                             [--num_workers NUM_WORKERS] [--lr LR]
                             [--beta1 BETA1] [--beta2 BETA2] [--mode MODE]
                             [--model_path MODEL_PATH]
                             [--sample_path SAMPLE_PATH]
                             [--image_path IMAGE_PATH] [--log_step LOG_STEP]
                             [--sample_step SAMPLE_STEP]
ipykernel_launcher.py: error: unrecognized arguments: -f /Users/dti/Library/Jupyter/runtime/kernel-0a3c5ccc-79ba-4805-8668-2c85aa0e488d.json

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

I used my images(128x128, RGB, 24files). 
What's wrong with me?

**Comment by yunjey** [comment]
@bemoregt 
It's argparse error. You entered the keyword incorrectly. 
You may enter the white space in the command.

**Comment by bemoregt** [comment]
Thanks. I fixed it. 

나의 iPhone에서 보냄

2017. 9. 29. 오후 7:47 yunjey <notifications@github.com> 작성:

**Comment by yunjey** [comment]
@bemoregt Great!

**Comment by bemoregt** [comment]
Thanks a lot~

나의 iPhone에서 보냄

2017. 9. 29. 오후 10:41 yunjey <notifications@github.com> 작성:
