### ISSUE TITLE
Input dimension to LSTM in language_model/main.py

### ISSUE THREAD

**Issue by donhk1011** [yunjey/pytorch-tutorial#73]
Hi,

The input dim to LSTM in the example is (batch, seq_len, input_size) which is different from  (seq_len, batch,  input_size) in the official documentation.

Could you please check what is right?

Thanks,

**Comment by yunjey** [comment]
@donhk1011 Please see [here](https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/02-intermediate/language_model/main.py#L32). I used `batch_first=True` in `nn.LSTM` for (batch, seq_len, input_size). There are two choices for dimension ordering of inputs. `batch_first=False` for (seq_len, batch, input_size) and `batch_first=True` for (batch, seq_len, input_size). I'm more familiar with the latter.
