### ISSUE TITLE
Readme for Image Captioning Tutorial

### ISSUE THREAD

**Issue by umerebryx** [yunjey/pytorch-tutorial#8]
Hi guys, 
Image captioning doesn't contain a main.py / main-gpu.py file as suggested by your main Readme file. It would be really helpful if you can add some instructions how to run inference on input images using existing models or start training on some custom dataset. 

Thanks

**Comment by yunjey** [comment]
@umerebryx, i will upload README.md for image captioning soon.

**Comment by jtoy** [comment]
+1

**Comment by yunjey** [comment]
I uploaded README.md for image captioning. It would be helpful.
