### ISSUE TITLE
Image Captioning Test Error

### ISSUE THREAD

**Issue by congve1** [yunjey/pytorch-tutorial#84]
When I test the model using jupyter notebook. I got the error below
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/disk/clw/pytorch-tutorial/tutorials/03-advanced/image_captioning/sample.py in <module>()
     95                         help='number of layers in lstm')
     96     args = parser.parse_args()
---> 97     main(args)

/disk/clw/pytorch-tutorial/tutorials/03-advanced/image_captioning/sample.py in main(args)
     59     # Generate caption from image
     60     feature = encoder(image_tensor)
---> 61     sampled_ids = decoder.sample(feature)
     62     sampled_ids = sampled_ids.cpu().data.numpy()
     63 

/disk/clw/pytorch-tutorial/tutorials/03-advanced/image_captioning/model.py in sample(self, features, states)
     66             inputs = self.embed(predicted)
     67             inputs = inputs.unsqueeze(1)                         # (batch_size, 1, embed_size)
---> 68         sampled_ids = torch.cat(sampled_ids, 1)                  # (batch_size, 20)
     69         return sampled_ids.squeeze()

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)
```
It seems there maybe someting wrong with the ` torch.cat() ` method. But When I use ` torch. stack() ` method, everything goes well. 
So maybe we should use the `torch.stack() ` instead.

**Comment by icfear** [comment]
If you are testing a single image, `sampled_ids = torch.cat(sampled_ids, 0) ` will do the trick. I suggest you to print `sampled_ids` before and after this operation and see the little change it brings to the table :).

**Comment by congve1** [comment]
@icfear 
I reviewed the code in `sample.py`. If just testing a single image, then `sampled_ids = torch.cat(sampled_ids, 0)` will correctly get the captions. But looking at the comments in `model.py`,  I still think that we should use `torch.stack` instead.

**Comment by yunjey** [comment]
Sorry for the late reply. This has been fixed in the current version.
