### ISSUE TITLE
cpu/gpu mixups?

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#9]
should main.gpu.py have cpu() calls in it?
https://github.com/yunjey/pytorch-tutorial/blob/master/tutorials/07%20-%20Bidirectional%20Recurrent%20Neural%20Network/main-gpu.py#L91

**Comment by yunjey** [comment]
Yes, you should. To compute `predicted == labels`,  both tensors corresponding to `predicted` and `labels` should be in same device (e.g. cpu or gpu). To execute `predicted.cpu()` makes the tensor in predicted move to cpu.
