### ISSUE TITLE
METEOR, Blue@k and CIDER metrics for image captioning

### ISSUE THREAD

**Issue by VisheshTanwar-IITR** [yunjey/pytorch-tutorial#91]
Hello @yunjey 

I want to calculate the meteor, cider, etc. to examine the image captioning accuracy.

How can I do it? Is there any source where I can get?

Thanks

**Comment by icfear** [comment]
You can use coco-caption evaluation code from [this adress](https://github.com/tylin/coco-caption). You have to save the caption and image ids as a json file with the following format; 
`[{"image_id": correct image id, "caption": "Generated caption"},...]`.
You can find a sample json file [here](https://github.com/tylin/coco-caption/tree/master/results)

**Comment by VisheshTanwar-IITR** [comment]
Thanks @icfear
