### ISSUE TITLE
pytorch_basics: Line 153, the input size must be 224x224

### ISSUE THREAD

**Issue by mirjalil** [yunjey/pytorch-tutorial#94]
In the pytorch basics, the input size must be 224x224. Currently , it is 256x256 and this will cause an error since the final linear layer will have size 2048, while the model expects it to be 512.

`images = Variable(torch.randn(10, 3, 224, 224))`

**Comment by yunjey** [comment]
@mirjalil Thanks a lot! The code was fixed.
