### ISSUE TITLE
[Image captioning] pack_packed wrong lengths

### ISSUE THREAD

**Issue by LapoFrati** [yunjey/pytorch-tutorial#95]
In the Image Captioning tutorial
in the DecoderRNN:

```
def forward(self, features, captions, lengths):
  embeddings = self.embed(captions)
  embeddings = torch.cat((features.unsqueeze(1), embeddings), 1)
  packed = pack_padded_sequence(embeddings, lengths, batch_first=True)
  hiddens, _ = self.lstm(packed)
  outputs = self.linear(hiddens[0])
  return outputs
```

 shouldn't the lenghts inside pack_padded be lenghts+1 to take into account the increased length due to the features added with cat?

e.g. (assuming numbers are captions, e is the embedding, f are the features and batch_size = 4)
if
```
embeds:
e(126)  e(1214)  e(14)    e(4033)
e(126)  e(6)     e(84)    e(4033)
e(126)  e(3002)  e(4033)  e(0)
e(126)  e(3002)  e(4033)  e(0)
```
has lengths = [4,4,3,3]
then
```
embeds_cat:
f_0  e(126)  e(1214)  e(14)    e(4033)
f_1  e(126)  e(6)     e(84)    e(4033)
f_2  e(126)  e(3002)  e(4033)  e(0)
f_3  e(126)  e(3002)  e(4033)  e(0) 
```
should have lengths = [5,5,4,4], right?

**Comment by LapoFrati** [comment]
After some more testing I've decided that the lengths shouldn't be changed since I don't want to use the last caption as an input to the lstm (the <end>).

**Comment by ghwatson** [comment]
@LapoFrati i was thinking the same thing as I went through this code...why wouldn't you want to use last word in the caption as input?

**Comment by sth4k** [comment]
@ghwatson understand the <eos> actually can be ignored. However, in this code implementation after torch.cat, the sequence will change from "<sos> token1 token2 ... tokenk<eos>" to "feature <sos> token1 token2 ..tokenk". The first step will be the "feature" vector and it's always used to predict <sos> only? From my understanding, the "feature" vector would make more sense if it works as the starting state of LSTM.

**Comment by LapoFrati** [comment]
Using the "feature vector" you have a training process that looks like:

- step 0: features + zeroes  -> caption_0 + state_0
- step 1: embed(caption_0) + state_0 -> caption_1 + state_1
- ...
- step n: embed(caption_n-1) + state_n-1 -> \<end\>

where zeroes is the default value if no state is provided.
@sth4k if you use the conv output as a "starting state" and manually provide it to the LSTM, what would you use as first input to the LSTM? A vector of constant values? I'm not an expert but I think both approaches should work in principle.

**Comment by sth4k** [comment]
> Using the "feature vector" you have a training process that looks like:
> 
> * step 0: features + zeroes  -> caption_0 + state_0
> * step 1: embed(caption_0) + state_0 -> caption_1 + state_1
> * ...
> * step n: embed(caption_n-1) + state_n-1 -> <end>
> 
> where zeroes is the default value if no state is provided.
> @sth4k if you use the conv output as a "starting state" and manually provide it to the LSTM, what would you use as first input to the LSTM? A vector of constant values? I'm not an expert but I think both approaches should work in principle.

Hi LapoFrati, thanks for your reply. Somehow github eats my word <s.o.s> which is the starting of sentence token (in your case caption_0). so you can see, features + zeros will always be used to predict caption_0 which is basically a starting token (similar to eos). Does it make sense?
